"""Framework providers: Django, FastAPI, Flask."""

from __future__ import annotations

from pathlib import Path

from devforge.core.context import ProjectContext
from devforge.providers.base import Provider, QuestionSpec


class DjangoProvider(Provider):
    name = "django"
    display_name = "Django"
    category = "framework"
    description = "Django web framework"
    packages = ["django>=5.0"]
    capabilities = ["framework", "web", "orm"]

    def questions(self, context: ProjectContext) -> list[QuestionSpec]:
        if context.framework != "django":
            return []
        return [
            QuestionSpec(
                key="django_drf",
                prompt="Include Django REST Framework?",
                kind="confirm",
                default=True,
            ),
            QuestionSpec(
                key="django_admin",
                prompt="Enable Django admin?",
                kind="confirm",
                default=True,
            ),
        ]

    def packages_for(self, context: ProjectContext) -> list[str]:
        pkgs = list(self.packages)
        if context.extras.get("django_drf", False):
            pkgs.append("djangorestframework>=3.15")
        db = context.database
        # drivers resolved here so user never picks them manually
        if db == "postgresql" and "psycopg[binary]>=3.1" not in pkgs:
            pkgs.append("psycopg[binary]>=3.1")
        if db == "mysql" and "mysqlclient>=2.2" not in pkgs:
            pkgs.append("mysqlclient>=2.2")
        return pkgs

    def environment(self, context: ProjectContext) -> dict[str, str]:
        return {"DJANGO_SETTINGS_MODULE": "src.settings"}

    def generate(
        self, context: ProjectContext, project_dir: Path, files: dict[str, str]
    ) -> dict[str, str]:
        if context.framework != "django":
            return files
        pkg = context.package_name
        use_drf = context.extras.get("django_drf", True)
        files["src/__init__.py"] = ""
        files["src/manage.py"] = (
            "#!/usr/bin/env python\n"
            "import os, sys\n"
            "def main():\n"
            '    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "src.settings")\n'
            "    from django.core.management import execute_from_command_line\n"
            "    execute_from_command_line(sys.argv)\n"
            'if __name__ == "__main__":\n'
            "    main()\n"
        )
        installed_apps = (
            "[\n"
            '    "django.contrib.admin",\n'
            '    "django.contrib.auth",\n'
            '    "django.contrib.contenttypes",\n'
            '    "django.contrib.sessions",\n'
            '    "django.contrib.messages",\n'
            '    "django.contrib.staticfiles",\n'
            + ('    "rest_framework",\n' if use_drf else "")
            + f'    "{pkg}",\n'
            + "]\n"
        )
        files["src/settings.py"] = (
            '"""Django settings (generated by DevForge)."""\n'
            "import os\n"
            "from pathlib import Path\n"
            "BASE_DIR = Path(__file__).resolve().parent.parent\n"
            'SECRET_KEY = os.environ.get("SECRET_KEY", "dev-insecure-key")\n'
            'DEBUG = os.environ.get("DEBUG", "True") == "True"\n'
            'ALLOWED_HOSTS = ["*"]\n'
            f"INSTALLED_APPS = {installed_apps}\n"
            "MIDDLEWARE = [\n"
            '    "django.middleware.security.SecurityMiddleware",\n'
            '    "django.contrib.sessions.middleware.SessionMiddleware",\n'
            '    "django.middleware.common.CommonMiddleware",\n'
            '    "django.middleware.csrf.CsrfViewMiddleware",\n'
            '    "django.contrib.auth.middleware.AuthenticationMiddleware",\n'
            '    "django.contrib.messages.middleware.MessageMiddleware",\n'
            "]\n"
            'ROOT_URLCONF = "src.urls"\n'
            "DATABASES = {\n"
            '    "default": {\n'
            '        "ENGINE": "django.db.backends.sqlite3",\n'  # noqa: E501
            '        "NAME": os.environ.get("DATABASE_URL", str(BASE_DIR / "db.sqlite3")),\n'  # noqa: E501
            "    }\n"
            "}\n"
            "CACHES = {\n"
            '    "default": {\n'
            '        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",\n'  # noqa: E501
            '        "LOCATION": os.environ.get("REDIS_URL", ""),\n'
            "    }\n"
            "}\n"
        )
        files["src/urls.py"] = (
            "from django.contrib import admin\n"
            "from django.urls import path\n"
            "from . import views\n"
            "urlpatterns = [path('admin/', admin.site.urls), path('', views.health)]\n"
        )
        files["src/views.py"] = (
            "from django.http import JsonResponse\n"
            "def health(request):\n"
            '    return JsonResponse({"status": "ok"})\n'
        )
        files["src/main.py"] = '"""Entry point."""\nprint("hello from django project")\n'
        return files


class FastAPIProvider(Provider):
    name = "fastapi"
    display_name = "FastAPI"
    category = "framework"
    description = "FastAPI framework"
    packages = ["fastapi>=0.110", "uvicorn[standard]>=0.29"]
    capabilities = ["framework", "web", "api"]

    def packages_for(self, context: ProjectContext) -> list[str]:
        pkgs = list(self.packages)
        if context.database == "postgresql":
            pkgs.append("psycopg[binary]>=3.1")
            pkgs.append("sqlalchemy>=2.0")
        if context.database == "mysql":
            pkgs.append("pymysql>=1.1")
            pkgs.append("sqlalchemy>=2.0")
        if context.authentication == "jwt":
            pkgs.append("python-jose[cryptography]>=3.3")
            pkgs.append("passlib[bcrypt]>=1.7")
        return pkgs

    def generate(
        self, context: ProjectContext, project_dir: Path, files: dict[str, str]
    ) -> dict[str, str]:
        if context.framework != "fastapi":
            return files
        files["src/__init__.py"] = ""
        files["src/main.py"] = (
            "from fastapi import FastAPI\n"
            f'app = FastAPI(title="{context.name}")\n'
            '@app.get("/health")\n'
            "def health():\n"
            '    return {"status": "ok"}\n'
        )
        files["src/app/__init__.py"] = ""
        files["src/app/main.py"] = 'from src.main import app\n__all__ = ["app"]\n'
        return files


class FlaskProvider(Provider):
    name = "flask"
    display_name = "Flask"
    category = "framework"
    description = "Flask microframework"
    packages = ["flask>=3.0"]
    capabilities = ["framework", "web"]

    def packages_for(self, context: ProjectContext) -> list[str]:
        pkgs = list(self.packages)
        if context.database == "postgresql":
            pkgs.append("psycopg[binary]>=3.1")
        if context.database == "mysql":
            pkgs.append("pymysql>=1.1")
        return pkgs

    def generate(
        self, context: ProjectContext, project_dir: Path, files: dict[str, str]
    ) -> dict[str, str]:
        if context.framework != "flask":
            return files
        files["src/__init__.py"] = ""
        files["src/app.py"] = (
            "from flask import Flask, jsonify\n"
            "app = Flask(__name__)\n"
            '@app.get("/health")\n'
            "def health():\n"
            '    return jsonify(status="ok")\n'
        )
        files["src/main.py"] = (
            'from src.app import app\nif __name__ == "__main__":\n    app.run()\n'
        )
        return files


class NoneFrameworkProvider(Provider):
    name = "none-framework"
    display_name = "None"
    category = "framework"
    description = "No framework (plain Python)"
    capabilities = ["framework"]

    def generate(
        self, context: ProjectContext, project_dir: Path, files: dict[str, str]
    ) -> dict[str, str]:
        if context.framework not in ("none", "none-framework", "", None):
            return files
        files["src/__init__.py"] = ""
        files["src/main.py"] = (
            'def main():\n    print("hello")\n\nif __name__ == "__main__":\n    main()\n'
        )
        return files
