"""Generator engine — merges composable provider contributions."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from devforge.core.context import ProjectContext
from devforge.core.environment import base_env, merge_env, render_env
from devforge.core.exceptions import GenerationError
from devforge.core.manifest import write_manifest
from devforge.core.registry import ProviderRegistry
from devforge.core.resolver import DependencyResolver
from devforge.core.template_engine import TemplateEngine
from devforge.core.validator import Validator


@dataclass
class GenerationPlan:
    files: dict[str, str] = field(default_factory=dict)
    packages: list[str] = field(default_factory=list)
    env: dict[str, str] = field(default_factory=dict)


@dataclass
class GenerationResult:
    project_dir: Path
    files: list[str]
    packages: list[str]


PYPROJECT_TEMPLATE = """[project]
name = "{slug}"
version = "0.1.0"
description = "{name} — generated by DevForge"
readme = "README.md"
requires-python = ">={python_version}"
dependencies = [
{deps}
]

[project.optional-dependencies]
dev = ["pytest>=8.0", "ruff>=0.4"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

{ruff_section}
{pytest_section}
"""

README_TEMPLATE = """# {name}

Generated with [DevForge](https://github.com/example/devforge).

## Stack

{stack_lines}

## Quick start

```bash
python -m venv .venv
source .venv/bin/activate
pip install -e ".[dev]"
cp .env.example .env
{run_command}
```

## Project layout

```
{layout}
```
"""


class Generator:
    """Provider-agnostic generator: core merges, providers contribute."""

    def __init__(
        self,
        registry: ProviderRegistry,
        template_engine: TemplateEngine | None = None,
        devforge_version: str = "0.5.0",
    ) -> None:
        self.registry = registry
        self.templates = template_engine or TemplateEngine()
        self.resolver = DependencyResolver(registry)
        self.validator = Validator(registry)
        self.devforge_version = devforge_version

    # -- planning (pure, used by --dry-run) --

    def plan(self, context: ProjectContext) -> GenerationPlan:
        resolution = self.resolver.resolve(context)
        ctx = resolution.context
        errors = self.validator.validate(ctx)
        # broker choice deferred to wizard; plan tolerates it for dry-run display
        non_broker_errors = [e for e in errors if "broker" not in e.lower()]
        if non_broker_errors:
            raise GenerationError("; ".join(non_broker_errors))

        files: dict[str, str] = {}
        active = self.registry.active_for(ctx)

        # 1. provider file contributions (composable, no template explosion)
        for provider in active:
            provider.generate(ctx, Path("."), files)

        # fallback source scaffold when no framework provider contributed files
        if "src/main.py" not in files:
            files["src/__init__.py"] = ""
            files["src/main.py"] = (
                'def main():\n    print("hello")\n\nif __name__ == "__main__":\n    main()\n'
            )

        # 2. merged environment
        env = base_env()
        for provider in active:
            env = merge_env(env, provider.environment(ctx) or {})
        # ensure expected keys exist
        env.setdefault("DEBUG", "True")
        env.setdefault("SECRET_KEY", "change-me")
        files[".env"] = render_env(env)
        # .env.example blanks secrets but keeps keys
        example = {k: ("" if "SECRET" in k or "PASSWORD" in k else v) for k, v in env.items()}
        files[".env.example"] = render_env(example)

        # 3. merged pyproject.toml dependencies
        packages = self.resolver.pip_packages(ctx)
        deps_block = "\n".join(f'    "{p}",' for p in packages)
        has_ruff = "ruff" in {p.split("[")[0].split("=")[0].split(">")[0] for p in packages} or (
            ctx.formatter == "ruff"
        )
        has_pytest = ctx.testing == "pytest"
        ruff_section = (
            '[tool.ruff]\ntarget-version = "py311"\nline-length = 100\n' if has_ruff else ""
        )
        pytest_section = '[tool.pytest.ini_options]\ntestpaths = ["tests"]\n' if has_pytest else ""
        py_version = ctx.python_version if ctx.python_version != "3" else "3.11"
        files["pyproject.toml"] = PYPROJECT_TEMPLATE.format(
            slug=ctx.slug,
            name=ctx.name,
            python_version=py_version,
            deps=deps_block,
            ruff_section=ruff_section,
            pytest_section=pytest_section,
        )

        # 4. README
        stack_lines = "\n".join(f"- {p.display_name} ({p.category})" for p in active) or "- Python"
        run_command = self._run_command(ctx)
        layout = "src/\\ntests/\\npyproject.toml\\n.env.example"
        files.setdefault(
            "README.md",
            README_TEMPLATE.format(
                name=ctx.name, stack_lines=stack_lines, run_command=run_command, layout=layout
            ),
        )

        # 5. docker compose (merged from docker_service hooks)
        if ctx.docker:
            files.setdefault("Dockerfile", self._default_dockerfile(ctx))
            files.setdefault("docker-compose.yml", self._compose_yaml(ctx, active))
            files.setdefault(
                ".dockerignore",
                "__pycache__/\n*.pyc\n.venv/\n.git/\n.env\n.pytest_cache/\n",
            )

        # 6. gitignore (provider-aware merge)
        files.setdefault(".gitignore", self._gitignore(ctx, active))

        return GenerationPlan(files=files, packages=packages, env=env)

    # -- execution --

    def generate(
        self,
        context: ProjectContext,
        output_dir: Path,
        *,
        overwrite: bool = False,
        install: bool = False,
    ) -> GenerationResult:
        plan = self.plan(context)
        resolution = self.resolver.resolve(context)
        ctx = resolution.context
        project_dir = output_dir / ctx.slug if output_dir.name != ctx.slug else output_dir
        # safety: never silently overwrite
        if project_dir.exists() and any(project_dir.iterdir()) and not overwrite:
            raise GenerationError(
                f"Directory '{project_dir}' already contains files. "
                "Re-run with overwrite=True or choose another directory."
            )
        project_dir.mkdir(parents=True, exist_ok=True)
        written: list[str] = []
        for rel, content in plan.files.items():
            target = project_dir / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            if target.exists() and not overwrite:
                continue
            target.write_text(content, encoding="utf-8")
            written.append(rel)

        # manifest
        write_manifest(project_dir, ctx, self.devforge_version)
        written.append(".devforge/project.yaml")

        # git init
        if ctx.git:
            self._git_init(project_dir)

        if install and plan.packages:
            from devforge.core.installer import install_packages

            install_packages(plan.packages, target_dir=project_dir)

        return GenerationResult(
            project_dir=project_dir, files=sorted(written), packages=plan.packages
        )

    # -- helpers --

    def _run_command(self, ctx: ProjectContext) -> str:
        if ctx.framework == "django":
            return "python src/manage.py runserver"
        if ctx.framework == "fastapi":
            return "uvicorn app.main:app --reload"
        if ctx.framework == "flask":
            return "flask --app src/app run"
        return "python -m src.main"

    def _default_dockerfile(self, ctx: ProjectContext) -> str:
        return (
            f"FROM python:{ctx.python_version}-slim\n"
            "WORKDIR /app\n"
            "COPY pyproject.toml README.md ./\n"
            "COPY src/ ./src/\n"
            "RUN pip install --no-cache-dir -e .\n"
            'CMD ["python", "-m", "src.main"]\n'
        )

    def _compose_yaml(self, ctx: ProjectContext, active) -> str:
        import yaml

        services: dict = {
            "app": {
                "build": ".",
                "env_file": ".env",
                "volumes": [".:/app"],
                "ports": ["8000:8000"],
                "depends_on": [],
            }
        }
        for provider in active:
            svc = provider.docker_service(ctx)
            if svc:
                name = svc.pop("name", provider.name)
                services[name] = svc
                if name != "app":
                    services["app"]["depends_on"].append(name)
        if not services["app"]["depends_on"]:
            del services["app"]["depends_on"]
        return yaml.safe_dump({"version": "3.9", "services": services}, sort_keys=False)

    def _gitignore(self, ctx: ProjectContext, active) -> str:
        lines = [".env", ".venv/", "__pycache__/", "*.pyc", ".pytest_cache/", ".ruff_cache/"]
        if ctx.framework == "django":
            lines += ["*.log", "staticfiles/", "media/"]
        if ctx.database == "sqlite":
            lines += ["*.sqlite3", "*.db"]
        for p in active:
            if p.name == "pre-commit":
                lines.append(".pre-commit-config.yaml.bak")
        return "\n".join(sorted(set(lines))) + "\n"

    def _git_init(self, project_dir: Path) -> None:
        import subprocess

        try:
            subprocess.run(["git", "init"], cwd=str(project_dir), capture_output=True, check=False)
        except FileNotFoundError:
            pass
